[project]
name = "poker-rankings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.1",
    "scipy>=1.16.0",
    "trueskill>=0.4.5",
]
